### ISSUE TITLE
document how to build with clang when GCC < 4.8 is installed

### ISSUE THREAD

**Issue by nurpax** [Andersbakken/rct#17]
I'm trying to build rtags with clang-3.4 installed from Ubuntu with GCC 4.6 installed, but I'm hitting this error:

```
android-main-2014-11-21 (release):~/t/rtags/build$ cmake ..
-- LLVM llvm-config found at: /usr/bin/llvm-config-3.4
-- Using Clang version 3.4 from /usr/lib/llvm-3.4/include/clang-c/
CMake Error at src/rct/rct.cmake:189 (message):
  C++11 support not detected.  rct requires a modern compiler, GCC >= 4.8 or
  Clang >= 3.2 should suffice
Call Stack (most recent call first):
  src/rct/CMakeLists.txt:2 (include)


-- Configuring incomplete, errors occurred!
```

Unfortunately I have no idea to build rtags with clang (e.g. override default g++).  I'm not sure if installing gcc 4.8 is easy on my older Ubuntu.  It's probably just a cmake config step away.

This would be nice to document in the README.

**Comment by mgulick** [comment]
In case anyone else hits this issue building on an older system (I was building on a Debian 7 system w/ gcc 4.7), without going into all the gory details, here's the key :
* Build gcc 4.9 and install it into a separate prefix.  This should be straightforward and there are numerous guides online.
* Build llvm/clang 3.7.
  * I downloaded the following llvm packages:
    * Clang source code
    * LLVM source code
    * Compiler RT source code
    * LibC++ source code
    * LibC++ ABI source code
    * Clang Tools Extra

  These packages need to be extracted/moved into specific directories.  See the link at the end of this comment for details.
  **Important:** when building clang, you need to explicitly use the gcc 4.9 libc headers, as using the system-default gcc 4.7 headers will result in the std::chrono::duration error mentioned in earlier comments.  The actual cmake line I used was:
  ```
  cmake ../src/llvm -G Ninja -DCMAKE_C_COMPILER=$GCC49ROOT/bin/gcc \
    -DCMAKE_CXX_COMPILER=$GCC49ROOT/bin/g++ \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_INSTALL_PREFIX=$clangInstall \
    -DGCC_INSTALL_PREFIX=$GCC49ROOT \
    -DCMAKE_CXX_LINK_FLAGS="-L${GCC49ROOT}/lib64 -Wl,-rpath,${GCC49ROOT}/lib64"
```
  where `$GCC49ROOT` is the gcc 4.9 install prefix that was used.  After that it was just `ninja` and `ninja install` to compile and install.  `$clangInstall` can be something like `/opt/llvm/3.7.0`.

* Build rtags
  I used a similar cmake command line for rtags:
```
  tar -xf rtags.tar.xz
  cd rtags
  mkdir build
  cd build
  cmake .. -DLLVM_CONFIG=$CLANG37ROOT/bin/llvm-config \
    -DCMAKE_C_COMPILER=$CLANG37ROOT/bin/clang \
    -DCMAKE_CXX_COMPILER=$CLANG37ROOT/bin/clang++ \
    -DCMAKE_CXX_LINK_FLAGS="-Wl,-rpath,$GCC49ROOT/lib64 -Wl,-rpath,$CLANG37ROOT/lib" \
    -DCMAKE_INSTALL_PREFIX=$rtagsInstall
  make -j8
  make install
```
  where `$CLANG37ROOT` is the clang install prefix, and `$GCC49ROOT` is the same as when building llvm.  `$rtagsInstall` can be something like `/opt/rtags`

I couldn't have figured this out without this page: http://btorpey.github.io/blog/2015/01/02/building-clang/

**Comment by cslux** [comment]
@mgulick Cool stuff! Maybe I'll try this. I just gave up at work to use rdm, debian 7 has such old packages in the repos it is a bit of a nightmare, but there is hope. Thanks for sharing. 

Better no indexer than working with eclipse. :-D
