### ISSUE TITLE
LICENSE.txt seems like it could use some TLC

### ISSUE THREAD

**Issue by jwatt** [Andersbakken/rct#47]
In LICENSE.txt looks like it's been cribbed from the "Sudo License" section of http://www.linfo.org/bsd_license.html but not modified properly. For example it still says:

```Products derived from this software may not be called "Sudo"```

and:

```Additionally, lsearch.c, fnmatch.c, getcwd.c, snprintf.c strcasecmp.c and fnmatch.3 bear the following UCB license```

(these files don't exist in the rct source).

**Comment by Andersbakken** [comment]
:-) Thanks.
