### ISSUE TITLE
Returning address of local temporary object

### ISSUE THREAD

**Issue by sztomi** [Andersbakken/rct#48]
clang 3.9 warns about the following (lots of instances, for example): https://github.com/Andersbakken/rct/blob/master/rct/Map.h#L49

```cpp
Value value(const Key &key, const Value &defaultValue = Value(), bool *ok = 0) const
    {
        typename Base::const_iterator it = Base::find(key);
        if (it == Base::end()) {
            if (ok)
                *ok = false;
            return defaultValue;
        }
        if (ok)
            *ok = true;
        return it->second;
    }
```

Since clang-3.9 is not released yet, this might be an error, but I do think that the compiler is right on this one. `defaultValue` is a lvalue reference, and the value is local to the function (since it's a parameter).

**Comment by Andersbakken** [comment]
But it doesn't return a reference. It returns a copy of Value. I don't
entirely see why this would be a problem.

Anders

**Comment by sztomi** [comment]
You are right, I missed that.
