### ISSUE TITLE
What's the difference between removeDirectory() in Rct and Path::rmdir()

### ISSUE THREAD

**Issue by Gei0r** [Andersbakken/rct#49]
While porting to windows, I stumbled upon the removeDirectory() function in Rct.h (implementation in Rct.cpp). It seems to have the same purpose as Path::rmdir(). Is there any difference between the two or can I implement one using the other?

**Comment by Andersbakken** [comment]
Good question indeed. I just killed Rct::removeDirectory and made
everything use Path::rmdir (though I took the implementation from
Rct::removeDirectory).

Thanks

Anders
